name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11','3.12','3.13']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Add PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        curl https://raw.githubusercontent.com/quickfix/quickfix/master/spec/FIX44.xml -o FIX44.xml
        pip install -r requirements.txt -U
        pip install pytest pytest-timeout pytest-asyncio # Ensure that pytest is installed

    - name: Run tests
      run: pytest -s --spec=FIX44.xml --timeout=90 -v # Use pytest instead of py.test
